### ISSUE TITLE
Getting a 403 error on all downloads

### ISSUE THREAD

**Issue by Delwin9999** [trakos/CFAN#10]
**CFAN Version:**
7256e64

**Operating System:** 
Windows 10 

**The issue you are experiencing:** 
Cannot download any mods

**How to recreate this issue:** 
Try to update EfficenSee

**CFAN error codes (if applicable):**
Failed to download "https://mods.factorio.com/api/downloads/data/mods/398/EfficienSee_1.0.39.zip?username=&token=" - error: The remote server returned an error: (403) Forbidden.

**Comment by trakos** [comment]
Can you try to launch the game, enter in-game mod manager (mods -> install mods), quit the game, and restart CFAN?

I have to improve the error message, but it basically means that no user auth token was found in your game config (and downloading mods from mods.factorio.com requires authorization).

**Comment by Delwin9999** [comment]
OK, that did it.  Thank you!

**Comment by trakos** [comment]
Thank you for letting me know about the problem.

Today I've added an error message on CFAN launch to avoid confusion for others ;)
