### ISSUE TITLE
No New Mods Or Updates To Existing Mods

### ISSUE THREAD

**Issue by thorman123** [trakos/CFAN#11]
0.1.1-0

Windows 10

No new mods or updates to existing mods

Open CFAN yourself!

None!

**Comment by trakos** [comment]
Sorry about that, I've noticed the error, but couldn't fix it earlier because I've had a long weekend.

Everything should work fine now. Thanks for letting me know.

There was an issue with one of the mod defining dependency in a non-standard way, causing the synchronization process to crash.
