### ISSUE TITLE
trakos.pl no longer owned.

### ISSUE THREAD

**Issue by Sacro** [trakos/CFAN#12]
Thanks for wanting to bring an issue to our attention!

**CFAN Version:** 0.1.3-0-gadfe769 (beta)

**Operating System:** Windows 10 x64 

**The issue you are experiencing:** Couldn't download http://cfan.trakos.pl/repo/repository_v2.tar.gz.

**How to recreate this issue:** Open CFAN, if open, click refresh

**CFAN error codes (if applicable):**

Looks like the domain is no longer owned, is there an alternate repo or is CFAN abandoned?

**Comment by Sacro** [comment]
Looks like someone has bought the domain it and got it going again.

**Comment by trakos** [comment]
Sorry about that. I missed the payment deadline and it was offline for a few days.

Thanks for the report.

**Comment by Myricaulus** [comment]
Sorry to say, but it happens again :-(

**Comment by trakos** [comment]
Fixed, though it wasn't the domain this time around.
