### ISSUE TITLE
Repo down again

### ISSUE THREAD

**Issue by Myricaulus** [trakos/CFAN#13]
Thanks for wanting to bring an issue to our attention!

CFAN Version: 0.1.3-0-gadfe769 (beta)

Operating System: Windows 7 x64

The issue you are experiencing: Couldn't download http://cfan.trakos.pl/repo/repository_v2.tar.gz.

How to recreate this issue: Open CFAN, if open, click refresh

CFAN error codes (if applicable):

Looks like the domain is no longer owned, is there an alternate repo or is CFAN abandoned?

**Comment by Myricaulus** [comment]
I currently try to build the cfan-netfan myself to generate a new repo tar.gz, but it seems outdated. No auth key token usage so far.

**Comment by trakos** [comment]
Hey,

it wasn't the domain this time, my vm wasn't started. My server had years of uptime, so autostart wasn't a thing. Thanks for letting me know.

If you still have problems running netfan, let me know (probably open a separate issue). Netfan isn't the most obvious thing to use, but I'm using release to generate the package, so it should be usable.

**Comment by Myricaulus** [comment]
I got it running, as you can see in the factorio forum. It was simply my own incompetence to get the netfan running, although i have the feeling that you should disable the generation of the non-v2 repo as it got me some errors regarding tar.gz generation of a cfans folder which did not exists, only cfans_v2 or something. Just letting you know. If you need any assistance on this project just let me know.
