### ISSUE TITLE
Maybe reduce the timeout for accessing the remote repo

### ISSUE THREAD

**Issue by Myricaulus** [trakos/CFAN#15]
CFAN Version: 0.1.3-0-gadfe769 (beta)

Operating System: Windows 7 x64

The issue you are experiencing: It takes eons to check if the remote repo is not available  

How to recreate this issue:  Click Refresh repo while it is not available and watch your beard grow longer

CFAN error codes (if applicable): none

**Comment by trakos** [comment]
Yeah, you're right. Fixed in 151e2798910013a009829e8ac0c476e3a574f740.
