### ISSUE TITLE
Error in Autoupdate: "Could not create SSL/TLS secure channel"

### ISSUE THREAD

**Issue by thehaggardnerd** [trakos/CFAN#21]
**CFAN Version: 0.1.4-0-g4129ddb(beta)
**Operating System: Windows 10 Home, 10.0.17134 build 17134

**The issue you are experiencing: Autoupdate does not want to work.  Upon opening CFAN, a window pops up that says:
Error!
Error in autoupdate:  The request was aborted: Could not create SSL/TLS secure channel
![image](https://user-images.githubusercontent.com/40702343/42111497-b3152630-7bb2-11e8-973a-30d87639a7ec.png)

**How to recreate this issue: with "Check for CFAN updates on launch" enabled in settings, close and relaunch CFAN.exe
**CFAN error codes (if applicable): N/A (that i know of)

**Comment by trakos** [comment]
Thanks for the report! Github disabled TLS 1.1 some time ago, and TLS 1.2 is not enabled by default on older .NET/mono versions. I've added enabling it (in .NET versions new enough to support it).

You'd have to update manually though this time. Alternatively, updating .NET or mono should work as well.
