### ISSUE TITLE
Improper File System Transaction Tracking

### ISSUE THREAD

**Issue by bk5115545** [trakos/CFAN#3]
**CKAN Version:** 
0.0.2-0

https://github.com/trakos/CFAN/blob/master/Core/Net/NetFileCache.cs#L248-L258
should probably be changed to 

``` cpp
using (TransactionScope scope1 = new TransactionScope())
{
     if (move)
     {
         tx_file.Move(path, targetPath);
     }
     else
     {
         tx_file.Copy(path, targetPath, true);
      }
     scope1.Complete();
}
     // We've changed our cache, so signal that immediately.
     // OnCacheChanged(); // The Transactions library doesn't do lazy event propagation so we shouldn't need this if the FileSystemWatcher is working correctly
```

I'll look at getting my build environment setup.

**Comment by trakos** [comment]
I'm not sure what you mean, would adding TransactionScope make FileSystemWatcher pick up the changes? Otherwise I'm not sure what's the gain of adding transaction to a block with only one operation.

**Comment by bk5115545** [comment]
From the library's code, TxFileManager looks like it implements System.Transaction.IEnlistmentNotification which means that it probably relies on the signals from TransactionScope to know when to call callbacks.  I'll go verify this idea really fast.

**Comment by trakos** [comment]
Closing for now, feel free to open if you'll find anything :)
