### ISSUE TITLE
Program Crash at startup

### ISSUE THREAD

**Issue by Sebasch** [trakos/CFAN#4]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

0.0.2

**Operating System:** 

Win 10 x64

**The issue you are experiencing:** 

If the "mods" directory in Users/[User]/]AppData/Roaming/Factorio does not exist yet at startup the Program crashes with a System.Io.DirectoryNotFound Exception.

**How to recreate this issue:** 

Start the program without the mod directory created.

**Comment by trakos** [comment]
Sorry for that! Thanks for letting me know.

Fixed in 0.0.3
