### ISSUE TITLE
Some dialogues still have CKAN instead of CFAN

### ISSUE THREAD

**Issue by Sakata-MC** [trakos/CFAN#6]
Noticed on first start that a dialogue or two still had "CKAN" in the messages instead of "CFAN".  Can't recall which, but believe it was one of the 'update' messages.
Since I use both... was worried for a moment I'd ran the wrong one.

**Comment by trakos** [comment]
Hey,

you're right. It is fixed in 0.0.5.

I've found CKANs in:
- two in auto-update
- few in command line output
- some in logs

It should be all CFAN now.
