### ISSUE TITLE
Add addt'l docs for running under Linux

### ISSUE THREAD

**Issue by mynamewastaken** [trakos/CFAN#7]
Had to install mono (depending on your OS can be interesting). For me on Fedora 23 it was `dnf install mono`, otherwise check http://www.mono-project.com/docs/getting-started/install/linux/ and also needed to do a `mozroots --import --ask-remove` as cfan complained in terminal of issues making ssl connections (don't have scrollback, sorry).

Run app with `mono cfan.exe`.

After that was done gui loaded and opened fine but just sat there when trying to install mods, even with `--debug` added, only accidentailly found out when I tried `mono cfan.exe install bob` - it complained libcurl wasn't available. You'll need to install (again for me on Fedora 23) `dnf install libcurl-devel`.

**CKAN Version:** 
`mono cfan.exe version`
0.0.5-0-gb1eecbc (stable)

**Operating System:** 
`cat /etc/fedora-release`
Fedora release 23 (Twenty Three)

**Comment by trakos** [comment]
I apologize for the poor documentation. Today I've moved the wiki from CKAN and updated it a bit. I've switched my factorio post download link to this page: https://github.com/trakos/CFAN/wiki/Installing-CFAN .

If you feel that the Fedora page still misses some informations or is unclear, feel free to edit it (or let me know).

Thanks for brining this issue to my attention.

**Comment by mynamewastaken** [comment]
@trakos no problem - thank you for getting this setup! `CFAN` is the only thing that's worked for me so far, so I'm quite happy to find it!

**Comment by trakos** [comment]
I'm glad you like it!
