### ISSUE TITLE
Incorrect folder name in ZIP files

### ISSUE THREAD

**Issue by keryja** [trakos/CFAN#8]
**CFAN Version:**
(0.0.5) Little Biter 4

**Operating System:** 
Windows 7

**The issue you are experiencing:** 
Incorrect folder name for some mods (Such as [SmartTrains](https://github.com/Choumiko/SmartTrains)) 

**How to recreate this issue:**
1. Install SmartTrains
2. See contents of ZIP file
3. Observe incorrect folder name (`SmartTrains-v0.3` instead of `SmartTrains_0.3.91`)

**Comment by trakos** [comment]
Oops, you're right, it was github release version. I've fixed it now, but you'll probably need to use "Clear cache" button in settings (and remove broken mod first).

Sorry for that!
